
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/processor

    environment:
      - FLASK_ENV=development
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
